-- Multi-user support: the Party archetype. Data (operations, categories, groups, mappings) is
-- owned by a *party*, not directly by a user. A signing-in user gets a PERSON party of their own;
-- shared households are ORGANIZATION parties whose members join via party_membership. Identity
-- itself lives in Keycloak — app_user only mirrors the JWT subject/claims for FK purposes.

CREATE TABLE party (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(20)  NOT NULL CHECK (type IN ('PERSON', 'ORGANIZATION')),
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_user (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_sub      VARCHAR(36)  NOT NULL,
    email             VARCHAR(320) NOT NULL,
    display_name      VARCHAR(255) NOT NULL,
    personal_party_id BIGINT       NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_app_user_sub UNIQUE (keycloak_sub),
    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT fk_app_user_personal_party FOREIGN KEY (personal_party_id) REFERENCES party (id)
);

CREATE TABLE party_membership (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT      NOT NULL,
    user_id  BIGINT      NOT NULL,
    role     VARCHAR(20) NOT NULL CHECK (role IN ('OWNER', 'MEMBER')),
    CONSTRAINT uk_party_membership UNIQUE (party_id, user_id),
    CONSTRAINT fk_party_membership_party FOREIGN KEY (party_id) REFERENCES party (id),
    CONSTRAINT fk_party_membership_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX idx_party_membership_user ON party_membership (user_id);

-- Well-known default party (id 1). V11 assigns all pre-multi-user data to it; the first login
-- matching the `wealthstack.bootstrap.owner-email` property adopts it as their personal party.
INSERT INTO party (type, name) VALUES ('PERSON', 'Personal');
