CREATE TABLE banking_operations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date             DATE           NOT NULL,
    description      VARCHAR(1000)  NOT NULL,
    amount           NUMERIC(19, 2) NOT NULL,
    type             VARCHAR(255)   NOT NULL,
    bank_name        VARCHAR(255)   NOT NULL,
    account          VARCHAR(500)   NOT NULL,
    display_name     VARCHAR(500),
    category         VARCHAR(255)   NOT NULL,
    source_file_name VARCHAR(255)   NOT NULL,
    fingerprint      VARCHAR(64)    NOT NULL,
    occurrence       INTEGER        NOT NULL,
    CONSTRAINT uk_banking_operation_identity UNIQUE (fingerprint, occurrence)
);

CREATE TABLE account_mappings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_account  VARCHAR(500) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_account_mappings_raw_account UNIQUE (raw_account)
);
