CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name)
);

-- Category becomes a user-curated dictionary entry referenced by FK instead of an inline string.
-- The previous free-text bank-derived values are intentionally discarded (operations start
-- Uncategorized).
ALTER TABLE banking_operations ADD COLUMN category_id BIGINT;
ALTER TABLE banking_operations
    ADD CONSTRAINT fk_banking_operations_category
    FOREIGN KEY (category_id) REFERENCES categories (id);
ALTER TABLE banking_operations DROP COLUMN category;
