-- Categories are now bucketed into a user-managed grouping instead of the fixed spending/income/
-- others type (V6). Groups are a first-class, editable dictionary; reporting renders one section
-- per group. The three former types become seed groups so existing data keeps its grouping; the
-- user can then rename/add/delete groups freely.
CREATE TABLE category_groups (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_category_groups_name UNIQUE (name)
);

INSERT INTO category_groups (name) VALUES ('Spending'), ('Income'), ('Others');

ALTER TABLE categories ADD COLUMN group_id BIGINT;
ALTER TABLE categories
    ADD CONSTRAINT fk_categories_group
    FOREIGN KEY (group_id) REFERENCES category_groups (id);

-- Backfill each category into the seed group matching its old type, then drop the type column.
UPDATE categories SET group_id = (SELECT id FROM category_groups WHERE name = 'Spending') WHERE type = 'SPENDING';
UPDATE categories SET group_id = (SELECT id FROM category_groups WHERE name = 'Income')   WHERE type = 'INCOME';
UPDATE categories SET group_id = (SELECT id FROM category_groups WHERE name = 'Others')   WHERE type = 'OTHERS';
ALTER TABLE categories DROP COLUMN type;

-- Reporting groups by the category's group; index the FK so the aggregation join stays cheap.
CREATE INDEX idx_categories_group_id ON categories (group_id);
